import {useEffect,useState} from 'react';
import api from '../api/axios';
import toast from 'react-hot-toast';

export default function AdminProducts(){
 const [products,setProducts]=useState([]),[categories,setCategories]=useState([]),[editing,setEditing]=useState(null),[uploading,setUploading]=useState(false);
 const blank={name:'',description:'',price:'',image:'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80',brand:'JustBuy',category:'',stock:0,featured:false};
 const [form,setForm]=useState(blank);
 const load=async()=>{const [p,c]=await Promise.all([api.get('/products?limit=50'),api.get('/categories')]);setProducts(p.data.products);setCategories(c.data);};
 useEffect(()=>{load();},[]);
 const chooseImage=async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>5*1024*1024){toast.error('Image must be 5 MB or smaller');return;}if(!['image/jpeg','image/png','image/webp','image/gif'].includes(file.type)){toast.error('Please choose a JPG, PNG, WEBP or GIF image');return;}setUploading(true);try{const dataUrl=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});const {data}=await api.post('/uploads/product-image',{data:String(dataUrl).split(',')[1],mimeType:file.type});setForm(f=>({...f,image:data.url}));toast.success('Image uploaded');}catch(err){toast.error(err.response?.data?.message||'Image upload failed');}finally{setUploading(false);}};
 const submit=async e=>{e.preventDefault();try{if(editing)await api.put(`/products/${editing._id}`,form);else await api.post('/products',form);toast.success(editing?'Product updated':'Product created');setEditing(null);setForm(blank);load();}catch(err){toast.error(err.response?.data?.message||'Save failed');}};
 const edit=p=>{setEditing(p);setForm({...p,category:p.category?._id||p.category});};
 const del=async id=>{if(!confirm('Delete this product?'))return;try{await api.delete(`/products/${id}`);toast.success('Product deleted');load();}catch(e){toast.error('Delete failed');}};
 return <section className="section"><div className="container"><div className="page-heading"><span className="eyebrow">ADMIN</span><h1>Products</h1></div><form className="form-card admin-form" onSubmit={submit}><h2>{editing?'Edit product':'Add product'}</h2>{['name','brand','price','stock'].map(k=><label key={k}>{k[0].toUpperCase()+k.slice(1)}<input required={k!=='brand'} type={['price','stock'].includes(k)?'number':'text'} value={form[k]} onChange={e=>setForm({...form,[k]:['price','stock'].includes(k)?Number(e.target.value):e.target.value})}/></label>)}<label>Product image<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={chooseImage} disabled={uploading}/><small className="muted">JPG, PNG, WEBP or GIF · max 5 MB</small></label>{form.image&&<div className="admin-image-preview"><img src={form.image} alt="Product preview"/></div>}<label>Description<textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Category<select required value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="">Choose</option>{categories.map(c=><option key={c._id} value={c._id}>{c.name}</option>)}</select></label><label className="checkbox"><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/> Featured</label><div><button className="btn" disabled={uploading}>{editing?'Update':'Create'}</button>{editing&&<button type="button" className="btn btn-outline" onClick={()=>{setEditing(null);setForm(blank)}}>Cancel</button>}</div></form><div className="admin-table"><div className="table-row table-head"><span>Product</span><span>Price</span><span>Stock</span><span>Actions</span></div>{products.map(p=><div className="table-row" key={p._id}><span>{p.name}</span><span>₹{p.price.toLocaleString('en-IN')}</span><span>{p.stock}</span><span><button onClick={()=>edit(p)}>Edit</button> <button className="danger-btn" onClick={()=>del(p._id)}>Delete</button></span></div>)}</div></div></section>;
}
