import {createContext,useContext,useEffect,useState} from 'react';import api from '../api/axios';import toast from 'react-hot-toast';
const AuthContext=createContext(null);
export const AuthProvider=({children})=>{const [user,setUser]=useState(()=>{try{return JSON.parse(localStorage.getItem('user'))||null}catch{return null}});const [loading,setLoading]=useState(true);
useEffect(()=>{const boot=async()=>{if(!localStorage.getItem('token')){setLoading(false);return;}try{const {data}=await api.get('/auth/me');setUser(data.user);localStorage.setItem('user',JSON.stringify(data.user));}catch{logout();}finally{setLoading(false);}};boot();},[]);
const save=(data)=>{localStorage.setItem('token',data.token);localStorage.setItem('user',JSON.stringify(data.user));setUser(data.user);};
const login=async(credentials)=>{const {data}=await api.post('/auth/login',credentials);save(data);toast.success('Welcome back!');return data;};
const adminLogin=async(credentials)=>{const {data}=await api.post('/auth/admin-login',credentials);save(data);toast.success('Welcome to the admin portal');return data;};
const register=async(payload)=>{const {data}=await api.post('/auth/register',payload);save(data);toast.success('Account created!');return data;};
const logout=()=>{localStorage.removeItem('token');localStorage.removeItem('user');setUser(null);};
return <AuthContext.Provider value={{user,loading,login,adminLogin,register,logout,isAuthenticated:!!user,isAdmin:user?.role==='admin'}}>{children}</AuthContext.Provider>};
export const useAuth=()=>useContext(AuthContext);
